#!/bin/bash

SCRIPT_DIR=$(dirname $0)

cp "${SCRIPT_DIR}/TextMate-KeyBindings.dict" "${HOME}/Library/Application Support/TextMate/KeyBindings.dict"
cp "${SCRIPT_DIR}/DefaultKeyBinding.dict" "${HOME}/Library/KeyBindings/DefaultKeyBinding.dict"
cp "${SCRIPT_DIR}/com.googlecode.iterm2.plist" "${HOME}/Library/Preferences/com.googlecode.iterm2.plist"
cp "${SCRIPT_DIR}/prompt_config.sh" "${HOME}/.prompt_config.sh"
ln -s "${SCRIPT_DIR}/tm_properties" "${HOME}/.tm_properties"
"${SCRIPT_DIR}/gitconfig.sh" > "${HOME}/.gitconfig"

[[ -f /usr/local/bin/brew ]] || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

cd "${SCRIPT_DIR}" && brew bundle

"${SCRIPT_DIR}/macos"
