brew 'zsh-completions'
brew 'brew-cask-completion'
brew 'git'
brew 'gpg'

brew 'nvm'
brew 'go'
brew 'rustup'

brew 'watch'
brew 'tree'
brew 'jq'
brew 'direnv'

brew 'aws-sso-cli'
brew 'hub'
brew 'kubernetes-cli'
brew 'awscli'
brew 'terraform'
brew 'openconnect'
brew 'bitwarden-cli'

cask '1password'
cask 'launchbar'
cask 'iterm2'
cask 'zed'
cask 'visual-studio-code'
cask 'intellij-idea'
cask 'gitup'

cask 'docker'
cask 'postgres-unofficial'
cask 'postico'

cask 'anki'
cask 'thingsmacsandboxhelper'

cask 'google-chrome'
cask 'firefox'

cask 'discord'
cask 'zoom'
cask 'webex'

cask 'spotify'
cask 'steam'
cask 'iina'
cask 'transmission'

brew 'mas'

mas 'Moom',                 id: 419330170
mas 'Bitwarden',            id: 1352778147
mas 'The Unarchiver',       id: 425424353
mas 'Slack',                id: 803453959
mas 'Things',               id: 904280696
mas 'Xcode',                id: 497799835
mas '1Password for Safari', id: 1569813296
