#!/bin/bash

set -x
# SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
# SCRIPT_DIR="$(readlink "${BASH_SOURCE[0]}")"
# SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"
# SCRIPT_DIR="$(dirname "$(readlink "${BASH_SOURCE[0]}")")"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_CACHE_HOME="${HOME}/.cache"
mkdir -p "${XDG_CONFIG_HOME}" "${XDG_DATA_HOME}" "${XDG_CACHE_HOME}"

SCRIPT_DIR="${HOME}/.dotfiles"
echo "SCRIPT_DIR=${SCRIPT_DIR}"

sudo xcodebuild -license accept

# Homebrew installed for Apple Silicon? Intel? If neither, then install
[[ -f /opt/homebrew/bin/brew ]] || [[ -f /usr/local/bin/brew ]] || \
  /usr/bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

eval "$(/opt/homebrew/bin/brew shellenv)"
brew analytics off
brew bundle install --file="${SCRIPT_DIR}/Brewfile"


rustup-init
NVM_DIR="${XDG_CONFIG_HOME}/nvm"
mkdir "${NVM_DIR}"
